[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "toyc"
version = "0.1.4"
description = "A toy compiler with GPU backends (Vulkan + OpenGL)"
readme = "README.md"
license = { file = "toyc/LICENSE" }
requires-python = ">=3.10"
authors = [
  { name = "spy1345a"}
]
keywords = ["compiler", "gpu", "vulkan", "opengl", "toy"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",   
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Compilers",
]

# list any actual pip deps your code imports at runtime:
dependencies = [
    "pyopengl>=3.1",
    "vulkan>=1.3.275.1"
]

[project.urls]
Homepage = "https://github.com/spy1345a/toyc-repo"   
Repository = "https://github.com/spy1345a/toyc-repo"

[project.optional-dependencies]
vulkan = ["vulkan"]     
opengl = ["PyOpenGL"]

[tool.pyrefly]
search_path = [
    "toyc/gpu/vulkan",
]